### ISSUE TITLE
CA_CERTS needs to be set, no documentation or default.

### ISSUE THREAD

**Issue by DDevine** [Kami/django-yubico-authentication-backend#1]
Using django-yubico I found I could not authenticate because it would not connect to the Yubico server because httplib did not have the CA cert. The error suggested that I edit python-yubico-client httplib_ssl.py - this would works but it is not a good solution.

I found that httplib2 comes with a list of CAs in a text file, so I put CA_CERTS into my django settings.py  to linked to cacerts.txt in httplib2. 

Can this be added to the documentation? Perhaps the CAs list could be included in django-yubico or python-yubico-client which conveniently you maintain :D

**Comment by Kami** [comment]
Sorry for a (very) long delay. It looks like I never received a notification for this issue. I just noticed it today while cleaning this repo.

In any case, I'm closing this ticket because a new version of Python Yubico Client now uses `requests` library which ships with a default CA cert bundle so you don't need to manually set this variable.
